"""Elastic Security alert adapter — polls ES alert indices, normalizes to Aegis.

Supports two modes (configurable via es_alert_index):
  - Real Elastic Security: ".siem-signals-*" (reads actual detection alerts)
  - Synthetic/demo: "aegis-dev-alerts" (generated by generate_synthetic_alerts)

Architecture decision: Option 1+4 hybrid (Stage B, ADR-018).
"""

from datetime import UTC, datetime

from elasticsearch import Elasticsearch

from aegis.incidents.ingestion import ingest_alert
from aegis.incidents.schema import Incident


def normalize_elastic_alert(doc: dict) -> dict:
    """Translate ECS fields → Aegis fields dict."""
    rule = doc.get("rule", {})
    host = doc.get("host", {})
    user = doc.get("user", {})
    process = doc.get("process", {})
    source = doc.get("source", {})
    destination = doc.get("destination", {})
    file_ = doc.get("file", {})
    kibana = doc.get("kibana", {})

    alert_severity = rule.get("severity", kibana.get("alert", {}).get("severity"))

    return {
        "host": host.get("name", "unknown"),
        "user": user.get("name", "unknown"),
        "process": process.get("name", "unknown"),
        "pid": process.get("pid"),
        "parent_process": process.get("parent", {}).get("name"),
        "command_line": process.get("command_line"),
        "source_ip": source.get("ip"),
        "destination_ip": destination.get("ip"),
        "file_path": file_.get("path"),
        "source": "sysmon",
        "severity": _map_severity(alert_severity),
        "type": rule.get("name", "elastic-alert"),
        "elastic_alert_id": doc.get("_elastic_id"),
        "elastic_rule_id": rule.get("id"),
        "elastic_rule_name": rule.get("name"),
        "timestamp": doc.get("@timestamp"),
    }


def _map_severity(es_severity) -> str:
    """Map Elastic severity (0-100 or keyword) → Aegis (high/medium/low)."""
    if isinstance(es_severity, (int, float)):
        if es_severity >= 70:
            return "high"
        if es_severity >= 40:
            return "medium"
        return "low"
    mapping = {"critical": "high", "high": "high", "medium": "medium", "low": "low"}
    return mapping.get(str(es_severity).lower(), "medium")


class ElasticAlertPoller:
    """Polls ES security alert indices, normalizes to Aegis Alert model."""

    def __init__(self, es: Elasticsearch, alert_index: str, store, poll_interval: int = 30):
        self._es = es
        self._alert_index = alert_index
        self._store = store
        self._poll_interval = poll_interval

    def poll_once(self) -> list[Incident]:
        """One poll cycle: fetch uningested alerts → normalize → ingest."""
        body = {
            "query": {
                "bool": {
                    "must_not": {"term": {"aegis_ingested": True}},
                    "filter": {"range": {"@timestamp": {"gte": "now-1h"}}},
                }
            },
            "sort": [{"@timestamp": {"order": "asc"}}],
            "size": 10,
        }
        try:
            resp = self._es.search(index=self._alert_index, body=body)
        except Exception:
            return []

        incidents = []
        for hit in resp["hits"]["hits"]:
            alert_doc = hit["_source"]
            alert_doc["_elastic_id"] = hit["_id"]

            normalized = normalize_elastic_alert(alert_doc)
            incident = ingest_alert(
                store=self._store,
                source="elastic-security",
                fields=normalized,
                incident_type=normalized.get("type", "unknown"),
            )
            incidents.append(incident)

            # Mark as ingested for dedup
            try:
                self._es.update(
                    index=self._alert_index,
                    id=hit["_id"],
                    body={"doc": {"aegis_ingested": True, "aegis_incident_id": incident.id}},
                )
            except Exception:
                pass  # non-critical: worst case we re-ingest on next poll

        return incidents


# -- Synthetic alert generation (demo path) --

SYNTHETIC_ALERTS = [
    {
        "rule.name": "Suspicious Process Execution",
        "rule.severity": 80,
        "host.name": "DC01",
        "user.name": "Administrator",
        "process.name": "mimikatz.exe",
        "process.pid": 4212,
        "process.command_line": "mimikatz.exe sekurlsa::logonpasswords",
    },
    {
        "rule.name": "Lateral Movement via PsExec",
        "rule.severity": 90,
        "host.name": "DC01",
        "user.name": "SYSTEM",
        "process.name": "psexec.exe",
        "process.command_line": "psexec.exe \\\\192.168.56.106 cmd.exe",
        "destination.ip": "192.168.56.106",
    },
    {
        "rule.name": "Credential Dump Attempt",
        "rule.severity": 85,
        "host.name": "DC01",
        "user.name": "Administrator",
        "process.name": "procdump.exe",
        "process.pid": 7890,
        "process.command_line": "procdump.exe -ma lsass.exe",
        "file.path": "C:\\Windows\\Temp\\lsass.dmp",
    },
    {
        "rule.name": "Suspicious Network Connection",
        "rule.severity": 60,
        "host.name": "WORKSTATION-01",
        "user.name": "jsmith",
        "process.name": "powershell.exe",
        "process.pid": 3344,
        "destination.ip": "10.0.0.50",
    },
    {
        "rule.name": "Persistence Mechanism Detected",
        "rule.severity": 75,
        "host.name": "DC01",
        "user.name": "Administrator",
        "process.name": "reg.exe",
        "process.command_line": (
            "reg add HKLM\\Software\\Microsoft\\Windows\\CurrentVersion"
            "\\Run /v backdoor /d C:\\temp\\svc.exe"
        ),
        "file.path": "C:\\temp\\svc.exe",
    },
]


def generate_synthetic_alerts(es: Elasticsearch, index: str, count: int = 5) -> int:
    """Write synthetic alerts to the alert index for demo. Returns count written."""
    if not es.indices.exists(index=index):
        from aegis.incidents.es_store import _ALERT_MAPPINGS
        es.indices.create(index=index, mappings=_ALERT_MAPPINGS)

    written = 0
    for alert in SYNTHETIC_ALERTS[:count]:
        doc = {**alert, "@timestamp": datetime.now(UTC).isoformat()}
        es.index(index=index, document=doc, refresh=True)
        written += 1
    return written
